- src/bin/zmlocalconfig
`SoapHttpTransport` now uses `org.apache.http`
> ZCS-1373:zmlocalconfig --reload broken

- src/bin/zmtrainsa
The zmtrainsa wrapper script exports the spam and ham accounts to
a directory created with mktemp.  These will be created in /tmp which
may cause the root system to fill up if it was provisioned too small.
This patch allows to set the tmp directory separately for zmtrainsa
using the localconfig option zmtrainsa_tmp_directory which's value
defaults to ${zimbra_tmp_directory}/zmtrainsa.
A more general solution would be to add a
export TMPDIR=/opt/zimbra/tmp
to the .bashrc for the zimbra user but that might have unexpected
side effects.
> Bug 107462 use zimbra_tmp_directory for zmtrainsa

- src/bin/zmcontrol
Added a check to `zmcontrol` when attempting to stop services so
that it will not attempt to stop `zimbra-imapd` service if the
control file is not present.
> ZCS-1450 zimbra-imapd shutdown check

- src/libexec/zmstat-proc
- Zimbra's Jetty Distribution (9.3.5.v20151012) is installed in /opt/zimbra/common/jetty_home/ via a separate package.
- Zimbra specific webapps and other custom jetty configuration files will be installed in /opt/zimbra/jetty_base/.
- Now /opt/zimbra/mailboxd and /opt/zimbra/jetty are symbolic links that point to /opt/zimbra/jetty_base/.
> WIP: ZCS:2486 - Separated jetty.base and jetty.home, removed jetty-<version>

- src/libexec/zmsearchndelete
**Problem :** --searchdirectory option is not working in zmsearchndelete
**Fix :** In SearchDirectoryRequest one of the parameters is "types=accounts" but in script it is "types=account". Corrected the same.
**Testing done :** Tested script with --searchdirectory option.
**Testing needs to be done by QA :** extensively check all the script options with all possible values.
> NICPS-19 : corrected SearchDirectoryRequest to make --searchdirectory option work

- src/libexec/zmrestoreblob
This utility is used to check orphan headers for given account and if found any missing blobs, restores it from backup.  This utility does not restore shared blobs yet, we have added a separate ticket for that NICPS-231
Also added help option for this utility which shows help to the user.
#Usage
> NICPS-179: Blob Injection - Update script for Help and Backup path

- src/libexec/zmfixperms
Since this commit [1] the permissions of conf/templates on redhat/centos aren't properly set and zimbra user cannot read them.
This resulted in breakage of operation of automatic backup of conf/templates/ directory on the NG and ZSP.
[1] https://github.com/Zimbra/zm-build/commit/2a862832591afa3977c29b9382d79be80cd7cd6f#diff-bbb5838c36b21fa969f5cc2fc47b92fe
> Set permissions for conf/templates directory.

- cron_scripts/config/config.json
- cron_scripts/inactive_idle_accounts.pl
- cron_scripts/lib/ZCS/API.pm
- cron_scripts/lib/ZCS/CustomAPI.pm
This script will go through Zimbra's Internal LDAP and look for any account whose last login is greater than specified days (default is 97 days). and modify their account to 'pending' status.
You can pass 'last_login_days' as input parameter to this script.
Also you can pass 'new_status' parameter which will be considered to update user's account status else default would be 'locked' status.
make sure you have right configuration in config.json
> NICOPS-46 - Account Deactivation Script

- cron_scripts/close_inactive_accounts.pl
- cron_scripts/config/config.json
- cron_scripts/lib/ZCS/API.pm
- cron_scripts/lib/ZCS/CustomAPI.pm
This script will go through Zimbra's Internal LDAP and look for any account whose status is 'Inactive' and whose last login is greater than specified days (default is 187 days). and modify their account status to 'closed'.
You can pass 'last_login_days' as input parameter to this script. 
make sure you have right configuration in config.json
> NICOPS-47 - Account Closure Script

- src/bin/zmjava
Modified zmjava to include the zimbra ext dirs in classpath
Installed on ZCS with JDK 11 verified ZCS process starts without any issue
> ZCS-6714 Modifying java classpath to support JDK 11

- src/bin/zmjava
- src/bin/zmlocalconfig
- src/libexec/zmcheckversion
Fixed ClassNotFound error after Genesis run.
Reran the Genesis test cases and verified they are passing
> ZCS-6389 Fixing script path for JDK11

- src/libexec/zmreplchk
Always output name of LDAP server in error messages, include LDAP error string when unable to bind (helpful in case `$ldap_pass` at random LDAP master in a MMR setup is simply wrong)
> Mention LDAP server in error messages

- conf/zmlogrotate
Fixes https://bugzilla.zimbra.com/show_bug.cgi?id=106800 (Logrotate spews `gzip: stdin: file size changed while zipping`)
> Add "delaycompress" for Nginx logs

- src/libexec/zmqstat
The variable which is supposed to hold the "todo" recipients from the queue file is not initialized as an array reference.
Therefore, in peculiar cases where the record is missing in the queue file, zmqstat blows up halfway when trying to dereference as an array  something which is undefined.
Initializing it as an empty array reference at the beginning prevents that.
This sort of situation happens, for instance, if a queue object which already delivered to the intended recipients is move to the hold queue after the successful delivery but before being removed from the queue.
Calling zmqstat on the hold queue with `/opt/zimbra/libexec/zmqstat hold` outputs the summaries for the e-mails in the hold queue up to the first problematic one, when zmqstat blows up.
An example from the mailbox log …
> zmqstat: fix for partial output and crash caused by undefined initial state of a variable

- src/bin/zmplayredo
**Issue:** zmplayredo was failing in jdk 11 causing **ClassNotFoundException** as jdk11 does not have any ext directories. 
Fix: Removed '-Djava.ext.dirs' argument and replaced it with '-classpath' argument.
Tested genesis run  on zdev-vm016 and it is working as expected.
> ZCS-6953:fixing jdk11 classpath issue

- src/bin/zmmailboxdctl
issue : Young Gen Size JVM options was added which was somehow affecting garbage collection performance because the ratio of the heap dedicated to the young generation was quite high.
removed Young Gen Size  JVM arguments **-Xmn${javaXmn}m**. This is the summary after 1 hour of load test.
> summary +    699 in 00:00:06 =  119.6/s Avg:  1921 Min:     0 Max:  9828 Err:     0 (0.00%) Active: 0 Started: 200 Finished: 200
summary = 520455 in 01:00:09 =  144.2/s Avg:  1423 Min:     0 Max: 59644 Err:     0 (0.00%)
Tidying up ...    @ Thu Apr 18 09:37:05 EDT 2019 (1555594625855)
... end of run
Performance test ended at :- 04/18/2019 09:37:08
> ZCS-7106:Fix the GC optimisation argumnets

- src/bin/zmthrdump
- src/libexec/zmdiaglog
Fixed the code that generated heapdump and thread dump. These commands need to run now as root user.
Verified that threaddump and headpdump are generated
Verified the files output for zmdiaglog with 8.8.11 version.
> ZBUG-962 Fixing heapdump, thrddump

- src/bin/ldap.production
- src/bin/zmapachectl
- src/bin/zmclamdctl
- src/bin/zmfreshclamctl
- src/bin/zmlogswatchctl
- src/bin/zmmemcachedctl
- src/bin/zmopendkimctl
- src/bin/zmproxyctl
- src/bin/zmsaslauthdctl
- src/bin/zmswatchctl
- src/libexec/zmmtastatus
A number of utilities, in particular `/opt/zimbra/libexec/zmmtastatus` used a mechanism for checking whether something was running by checking whether a process - any process with the same PID as was recorded in a file was running.  This can lead to problems if a process dies or a system gets restarted and some unrelated process gets that PID.
For `zmmtastatus` we defer to Robert Scheck's fix to use `postfix status`.
Also addressed some other utilities where this PID file issue occurs and uses a more robust mechanism where the process for the process ID from the pid file is checked to see if it has the right name.
Also for `/opt/zimbra/bin/ldap` tidied up the indentation a lot, simplified the logic and reduced the potential waiting time for startup or shutdown to resolve.
> ZCS-7180 Bad PID checks

- src/libexec/zmjsprecompile
Made changes for zmprecompile to work for JDK11.
Tested by executing zmprecompile and its working fine.
> ZCS-7505: fixing classpath for JDK11

- src/bin/zmlocalconfig
Issue: Third-party vulnerabilities in dom4j
Fix: Upgrade dom4j to the latest version
> ZCS-8014: Third party vulnerabilities in dom4j

- src/bin/zmlocalconfig
Issue:
Vulnerabilities in older version 23.0 of Guava.
Fix:
Update version to 28.1-jre
> ZCS-8017: updating guava version to 28.1-jre from 23.0

- src/libexec/zmdiaglog
Issue:  Error for openjdk version 13 while running the command zmdiaglog
Fix: Added a check for jdk13 in the code base
> Unable to collect zmdiaglog after upgrading to ZCS 8.8.15 p5

- src/libexec/zmdiaglog
Issue: zmdiaglog not capturing top, ps and netstat on a non-mailbox server
Fix: collecting top, ps and netstat output if mailbox pid is not present
Testing done:
Tested on a non-mailbox server - top, ps and netstat commands are now getting collected
Tested on a mailbox server - top, ps, netstat, thread stats/stacks continue getting collected
> ZBUG-1055:zmdiaglog not capturing top, ps and netstat on non-mailbox

- src/bin/zmstat-chart-config
iostat recently changed the output and removed the colon that was previously part of the output. We need to look for Device now instead of Device:.
> Update to fix upstream change to iostat

- src/libexec/zmfixperms
NG-Backup is stopping because it cannot read files that have the wrong permissions.
Getting below warnings from backup notification.
Warnings:
- File /opt/zimbra/common/etc/openldap/slapd.conf is not readable
- File /opt/zimbra/common/etc/openldap/slapd.conf.default is not readable
- File /opt/zimbra/common/etc/openldap/slapd.ldif is not readable
- File /opt/zimbra/common/etc/openldap/slapd.ldif.default is not readable
> ZBUG-1441 : Default openldap configuration files with incorrect permissions

- src/bin/zmsshkeygen
**Problem :** 
SSH version in RHEL8 : OpenSSH_7.8p1
$ ssh -V
OpenSSH_7.8p1, OpenSSL 1.1.1 FIPS  11 Sep 2018
Starting with OpenSSH 7.8 by default, the key is created with the OpenSSH private key format instead of the OpenSSL PEM format.
Refer: https://www.openssh.com/txt/release-7.8
When we login to zimbra Admin , due to OpenSSH private key format, it is throwing below exception.
**Caused by**: java.io.IOException: Invalid PEM structure, '-----BEGIN...' missing
at ch.ethz.ssh2.crypto.PEMDecoder.parsePEM(PEMDecoder.java:138)
Please refer : https://github.com/hudson/ganymed-ssh-2/blob/5fe3de29a7499f4efbe959cf11fb92d28752852c/src/main/java/ch/ethz/ssh2/crypto/PEMDecoder.java#L141
**Solution:**
If key is in OpenSSH private key format we need to convert into OpenSSL PEM format.
> Convert OpenSSH private key to OpenSSL PEM format

- src/libexec/zmsyslogsetup
The gist of the issue is that both /var/log/zimbra.log & /var/log/zimbra-stats.log do not get written to after logrotate has ran; /etc/logrotate.d/zimbra
logrotate config file is looking for incorrect pid file (syslog.pid).   
Rsyslog's pid file name changed on CentOS 8/RHEL 8 versions and it is available as rsyslog.pid.
> ZBUG-1843: RHEL8 zimbra.log & zimbra-stats.log

- src/bin/zmskindeploy
**Problem:**
The following error was raised when zmskindeploy was executed.
```
Error: Unable to initialize main class com.zimbra.kabuki.tools.img.ImageMerger
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
```
**Fix:**
* Add `/opt/zimbra/lib/jars/commons-cli-1.2.jar` to classpath
> ZBUG-1146: fixed classpath in zmskindeploy

- src/libexec/zmmsgtrace
* Allow multiple --debug options
* s/statusmsg/statusMsg/g
* Save msg parsed from log line when first encountered
* Avoid uninitialized warns
* Add vim style hint to expand tabs
One outstanding question is whether or not to display the time the message left the particular queue being reported. That would break the output format, but would show the last time a delivery attempt was deferred.
> ZBUG-1319: Output deferred messages in zmmsgtrace

- src/libexec/zmfixperms
Issue :- zmfixperms script does not fix .saveconfig directory ownership. I am able to reproduce this issue on zcs 8.8.15 p26.
Expected output: zmfixperms should change the ".saveconfig" ownership to zimbra.
Solution : Added condition to change permission of .saveconfig directory to zimbra user when running the script
> ZBUG-2492 : Added condition to change permission to zimbra

- src/libexec/zmsaupdate
Problem: The --allowplugins option is now considered harmful by the SpamAssassin developers. If one really wishes to use it, they must specify --reallyallowplugins.
Fix: Added support for an LC option to use --reallyallowplugins in case customers need it.
Testing: See [ZBUG-2358](https://jira.corp.synacor.com/browse/ZBUG-2358?focusedCommentId=1665520&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1665520) for details.
> ZBUG-2358: sa-update --allowplugins workaround

- src/bin/zmresolverctl
Issue :- Due to the current regex, all disable and unwanted text extracted from the "/etc/resolv.conf" and injected into the Nginx resolver "/opt/zimbra/conf/nginx/resolvers.conf". 
```
root@mail:~# cat /etc/resolv.conf
nameserver 127.0.0.53
search myztestdom.com 
Actual:
root@mail:~# awk 'BEGIN{ns="";sep=""}/nameserver/{ns=ns sep $2;sep=" " }; END{ if (ns) {print "resolver " ns ";"} }' /etc/resolv.conf
resolver run 169.254.169.254 127.0.0.53;
root@mail:~#
Expected: 
root@mail:~# awk 'BEGIN{ns="";sep=""}/nameserver/{ns=ns sep $2;sep=" " }; END{ if (ns) {print "resolver " ns ";"} }' /etc/resolv.conf
resolver 127.0.0.53;
```
Solution : Updated regex to ignore commented lines. Will only consider the value when it matches at the beginning of input line 
```
root@mail:~# cat /etc/resolv.conf …
```
> ZBUG-2155: Regex correction in zmresolverctl

- src/libexec/zmconfigd
Issue: Used log4j version was below 2.17.1
Solution Upgraded log4j version to 2.17.1 as well as did implementation for same.
> ZCS-11112: Changes as per log4j-2.17.1

- src/libexec/zmrcd
**Feature**
Need API for scheduling HSM policy execution.
**Solution**
Created API for scheduling HSM policy and also created a script **zmschedulesmpolicy** for schedule from command line.
**Options for zmschedulesmpolicy**
**-l: list** - print existing schedule
**-h: help** - get help about zmschedulesmpolicy (default command)
**-f: flush** - remove current schedule (cancel all scheduled Storage Management policy)
**-e: edit** - edit current schedule with specified schedule
> ZCS-11481: Need API for scheduling HSM policy execution

- src/libexec/zmrcd
Feature :- Implemented regex for accepting all symbols and string in zmemail command.
> ZCS-11602 : Notification support for quarantined devices

- src/libexec/zmfixperms
- After upgrade proxy is not starting as log files are created with root permission
- issue is only happening in server where log rotation has not run once, as log rotation updates file permissions with zimbra user
Related PR https://github.com/Zimbra/zm-build/pull/242
> ZCS-12164 Change permission of nginx log files

- src/bin/zmonlyofficectl
**ZBUG-3263: Removing start|stop|status operations for onlyoffice spellchecker.**
- Spellchecker as a separate service is not needed Since v6.3.0 of onlyoffice/server
- Please refer - https://github.com/ONLYOFFICE/build_tools/issues/431
> ZBUG-3263: Removing start | stop | status functions for onlyoffice spellchecker.

- src/bin/zmcontrol
Follow proper semantic versioning for Daffodil patch.
With 8815/900, we are showing Patch P33 like this.
For Z10/Daffodil, while customer do zmcontrol -v, it will show patch version as per semantic, like below example
`Release 10.0.1.GA.4518.UBUNTU20_64 NETWORK edition `
> ZCS-13429:Semantic Versioning for Z10

- src/bin/zmjava
**Problem :**
User gets ClassNotFound exception while using zimbra-modules-porter package after NG Mailbox in place upgrade from 9.0 to 10.0 using --skip-ng-check option
Getting `Could not find or load main class com.zimbra.porter.ZPortCLIUtil
Caused by: java.lang.ClassNotFoundException: com.zimbra.porter.ZPortCLIUtil` error while importing data/setting using zmmodulesport if using already installed package.
**Fix :**
`zm-modules-porter` needs to add to the zimbra extensions path to load by mailbox. This has been already taking care by zimbra-modules-porter package https://github.com/Zimbra/zm-modules-porter/blob/develop/scripts/postinst.sh#LL14C20-L14C20. But this is getting overridden by upgrade (9.0 to 10.0) because latest zimbra-core package will be installed in the upgrade and this …
> ZCS-13314 : add zm-modules-porter to zimbra extensions path

- src/bin/zmcertmgr
zmcertmgr deploycrt self failing with OpenSSL 3.0.9
```
/opt/zimbra/bin/zmcertmgr deploycrt self
Installing imapd certificate '/opt/zimbra/conf/imapd.crt' and key '/opt/zimbra/conf/imapd.key'** Copying '/opt/zimbra/ssl/zimbra/server/server.crt' to '/opt/zimbra/conf/imapd.crt'** Copying '/opt/zimbra/ssl/zimbra/server/server.key' to '/opt/zimbra/conf/imapd.key'** Creating file '/opt/zimbra/ssl/zimbra/jetty.pkcs12'ERROR: openssl pkcs12 export to '/opt/zimbra/ssl/zimbra/jetty.pkcs12' failed(1):
Error creating PKCS12 MAC; no PKCS12KDF support?
Use -nomac if MAC not required and PKCS12KDF support not available.
C0D1C7FA4A7F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (PKCS12KDF : 192), …
```
> ZCS-13565 : use -fips option for PKCS12 file creation

- src/bin/zmcertmgr
by comparing pubkey (generic) instead of modulus (RSA specific).
> ZBUG-3135 zmcertmgr: make verifycrt work for non-RSA (ECDSA) certificates as well

- src/bin/zmcontrol
- src/bin/zmlicensectl
- We should not need of extra parameter of zmlicenseservice to pass zmlicensectl command
- Ability to control daemon service `zmlicensectl --service start|restart|stop`
- Ability to set license daemon service log level `zmlicensectl --service setLogLevel=INFO|DEBUG|ERROR|TRACE`
- Ability to set license daemon service mode `zmlicensectl --service setMode=offline|online`
Related PR : https://github.com/Zimbra/zm-license-daemon-service/pull/37
> ZCS-14533:Enhance zmlicensectl command to set log level and run in offline mode

- src/bin/zmlicensectl
**Issue :** Error: /opt/zimbra/license/config/license-daemon.cnf is missing in ZCS multi node setup
```
$ zmcontrol restart
Host *******
Stopping vmware-ha...Done.
Stopping zmconfigd...Done.
Stopping license-daemon...Failed.
Error: /opt/zimbra/license/config/license-daemon.cnf is missing.
Stopping zimlet webapp...Done.
Stopping zimbraAdmin webapp...Done.
Stopping zimbra webapp...Done.
Stopping service webapp...Done.
Stopping stats...Done.
Stopping onlyoffice...Done.
Stopping spell...Done.
Stopping snmp...Done.
Stopping cbpolicyd...Done.
Stopping archiving...Done.
Stopping opendkim...Done.
Stopping amavis...Done.
Stopping antivirus...Done.
Stopping antispam...Done.
Stopping proxy...Done.
Stopping memcached...Done.
Stopping mailbox...Done.
Stopping logger...Done.
Stopping dnscache...Done. …
```
> ZCS-14748:Fix license-daemon.cnf is missing error in ZCS multi node setup

- src/bin/zmcontrol
**Issue :** zmcontrol -v shows previous patch version in fresh installation even if latest patch is installed.
```
$ dpkg -l |grep -i "zimbra-patch\|zimbra-proxy-patch\|zimbra-mta-patch\|zimbra-ldap-patch"       
ii  zimbra-ldap-patch                          9.0.0.1688906705.p34-1.u20                                          amd64        Zimbra LDAP Patch
ii  zimbra-mta-patch                           9.0.0.1688906705.p34-1.u20                                          amd64        Zimbra MTA Patch
ii  zimbra-patch                               9.0.0.1694187731.p36-2.u20                                          amd64        Zimbra Network Patch
ii  zimbra-proxy-patch                         9.0.0.1688906705.p34-1.u20                                          amd64        Zimbra proxy Patch …
```
> ZCS-13844 : Modify zmcontrol to show the higher patch version

- src/libexec/zmsyslogsetup
Problem: When we run logrotate script(/etc/logrotate.d/zimbra) on rocky 8, it fails with following error. 
`error: /etc/logrotate.d/zimbra:5 unknown user 'USER'`
Fix: Since the script wasn't recognising the user therefore added the RHEL 8 conditional check for switching to zimbra user while execution of script.
> ZBUG-3281: Fix the issue "logrotate is failing on rocky/rhel 8".

- src/bin/zmcontrol
ZCS-14515 - License check fails with connection refused exception 
Fix - Reordered zmcontrol services. Ensured license daemon service starts before mailbox
> ZCS-14515 : Reordering zmcontrol order, starting daemon service before mailbox
