Zimbra/zm-core-utils

src/libexec/zmdiaglog

Update Zmdiaglog including configurations and log files for network-ng

[ZCS-3189] Update Zmdiaglog for 8.8

---

src/libexec/zmsearchndelete

Problem : Provide support for search and delete items in all users.
Fix :
1) Existing perl script available at http://zre-matrix.eng.zimbra.com:8080/@md=d&cd=/depot/psteam/main/tools/&c=79S@/depot/psteam/main/tools/zmsearchNdelete/?ac=83 is added.
2) usage info and details are given in script itself
Testing done : Tested script with single and multi-node environment.
Testing needed by QA : Extensive testing is needed on single and multi-node environment with different type of search criteria.
Linked PR - https://github.com/Zimbra/zm-build/pull/79
https://github.com/Zimbra/zm-core-utils/pull/10

NICPS-19 : Search and Delete

---

src/bin/zmcontrol

update script to check license file

NICPS-267: update script to check license file

---

src/bin/zmcontactbackup
src/bin/zmlocalconfig
src/libexec/zmreplchk

upgrade guava jar to version 23.0

ZCS-4723 Upgrading guava to 23

---

src/bin/zmconfigdctl

generating PR to merge fix done by @Prashantsurana  in bugfix branch to develop.

zcs-2672:  added -q2 option to nc to wait for response from zmconfigd

---

cron_scripts/config/config.json
cron_scripts/lib/ZCS/CustomAPI.pm
cron_scripts/password_expiration_notification.pl

We need to create a script that will allow us to detect in advance when a password is going to expire and notify end users that they need to change their password.
This script should take a configurable notification period, say two weeks, and then compare in LDAP the passwords creation date with the current date. If the password's creation date is older than the expiration limit, example 90 days (also configurable) - the notification period, then the script should notify the end user via SMS and email.
The message that is sent through SMS and/or email should also be configurable.
For example)
Password Expiration Limit is 90 days
Notification Period is 2 weeks or 14 days
Script should notify end users if their password creation date is 76 days or older.
The script will send a message once …

NICPS-297 - Password Expiration Notification Script

---

src/libexec/zmldapschema

Related PRs - https://github.com/Zimbra/zm-build/pull/135
https://github.com/Zimbra/zm-ldap-utilities/pull/6
https://github.com/Zimbra/zm-nicps/pull/6

NICPS-476: add new method to deploy legacy schema

---

src/libexec/zmjsprecompile

It was a regression because of the change in classpaths.
Updated the classpath like /opt/zimbra/common/jetty_home/

ZCS-2895: Bugfix

---

src/bin/zmjava
src/bin/zmmilterctl

**Problem:** milter server not starting.
**Fix:** removed "/opt/zimbra/conf" from classpath in zmmilter and added the same in zmjava
**Testing done:**
- Tested milter server status
- Tested mail delivery
**Testing to be done by QA:**
- verify milter status and mail delivery
- make sure nothing is broken

ZCS-6772 Getting error SMTP server reported: MESSAGE_NOT_DELIVERED in send message response.

---

src/libexec/zmdiaglog

Added an if clause to check for additional Java 11.0 version.

Update zmdiaglog script to include java version 11

---

src/libexec/zmstat-io
src/libexec/zmsyslogsetup

Fix for 
ZCS-6620: Getting perl related error message.
ZCS-6747: GetLoggerStatsRequest failing with error
ZCS-7614: Logger service not working.   
zmstat-io exhausting the disk space.
Thanks:
https://bugzilla.zimbra.com/show_bug.cgi?id=109205
https://forums.zimbra.org/viewtopic.php?t=65930

Ubuntu18 Logger fixes.

---

src/libexec/zmstatuslog

Printing the status of every docs server

ZBUG-1469: Fixed Zimbra Docs status page reporting by asking the docs status

---

src/bin/zmlocalconfig

verified by running /opt/qa/soapvalidator/data/soapvalidator/RestServlet/Mail/rest_httpheaders_bug67163.xml

ZCS-9125  Fixing CP for zmlocalconfig -l

---

src/bin/zmproxyctl

Taken comments from https://github.com/Zimbra/packages/commit/b77ea887311937c9bd62117165dc3435a5185087#commitcomment-42089097
and made changes accordingly.

ZCS-9857:Changes to nginx stop/reload

---

src/bin/cbpolicyd.sh

Added cbpolicyd.sh script which would support mysql DB for cbpolicyd

ZRFE-206: Added cbpolicyd.sh to support cbpolicyd with mysql database

---

src/libexec/zmjettyenablelogging

See a description in https://github.com/Zimbra/zm-build/pull/199

ZCS-11090: added zmjettyenablelogging

---

src/libexec/zmrcd

Related PRs:
https://github.com/Zimbra/zm-mailbox/pull/1314
https://github.com/Zimbra/zm-backup-store/pull/28

ZCS-11458: updated zmschedulebackup regex

---

src/bin/zms3config

**Problem Statement**
Create CLI utility to provide CLI interface for S3ConfigBucket Soap requests
**Solution**
Created new class and file named "VolumeS3ConfigCLI" which is CLI interface for s3BucketConfig requests

ZCS-11437 Add new CLI to manage global S3 buckets

---

src/bin/zms3config
src/libexec/zmrcd

ZCS-11314 Storage Management

---

src/bin/zmonlyofficectl
src/bin/zmrabbitmqctl
src/libexec/zmfixperms

Related PR's:
https://github.com/Zimbra/packages/pull/169
https://github.com/Zimbra/zm-build/pull/228

ZCS-11866 : added rabbitmqctl

---

src/libexec/zmrcd

Removed zmmdmnotificationmail which is not used any more

ZCS-12009 : Removed zmmdmnotificationmail
